### ISSUE TITLE
Stacking multiples of the same effect

### ISSUE THREAD

**Issue by joshwahwalters** [pmeas/pmeas-backend#20]
The application should be able to handle using multiples of the same effect. As of right now when two of the same effect are in the JSON "effects.txt" file only the last one listed is implemented.

**Comment by zhijazi** [comment]
This is because when translating to a dict, Python overwrites all keys of the same name with the latest value set for that key (i.e effect name). I'm thinking of a change to the communications format which will implicitly fix this while fixing the other bug of preserving order of applied effects. Don't try to fix this right now.
